Урок 9
MadinaAbd/Test-Guru pull request #12
Opened 2022-10-04 20:00 UTC by MadinaAbd

2022-10-05 03:58 UTC, VidgarVii requested changes

2022-10-05 03:58 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2022-10-05 03:58 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = User.find(params[:id])
params[:id] для этого контроллера будет служить для поиска теста, а не юзера.
Пока можешь брать любого существующего юзера. Потом сделаем система аутентификации

2022-10-05 03:58 UTC, VidgarVii commented on app/models/test.rb
> +  def self.list_by_category(title)
методы пишут после скоупов

2022-10-05 03:58 UTC, VidgarVii commented on app/models/test_passage.rb
> +    self.current_question = next_question
уже определён колбек для установки current_question. Не стоит распылять одну обязанность по всему коду

2022-10-05 03:58 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
здесь хорошо бы учесть ситуацию когда в `answer_ids` прийдет `nil`
код при этом не должен падать

2022-10-05 03:58 UTC, VidgarVii commented on config/routes.rb
> +      post :start, on: :member
поправь отступ

2022-10-05 03:58 UTC, VidgarVii commented on config/routes.rb
> +    end
для 1 строки можно использовать синтаксис как на 8 строке

2022-10-05 03:58 UTC, VidgarVii commented on config/routes.rb
зачем везде перед закрывающем блоком оставляешь пустую строку? Такого нет правила в рубокопе.
Пользуйся рубокопом!

2022-10-06 07:06 UTC, VidgarVii requested changes

2022-10-06 07:06 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: "Вопрос удален"
лчше отправить юзера на страницу теста.

2022-10-06 07:06 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
не исправил
https://github.com/MadinaAbd/Test-Guru/pull/12#discussion_r987515339

2022-10-06 07:06 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort && answer_ids.present?
не уверен, что код тестировался.
Если answer_ids будет нил, то до второго условия не дойдёт проверка. Так как тут будет ошибка еще на первом условии

2022-10-06 07:06 UTC, VidgarVii commented on app/models/test_passage.rb
> +
надо исправить отступы. Пользуйся рубокопом!

2022-10-06 07:06 UTC, VidgarVii commented on app/models/test_passage.rb
> +  end
а где установка следующего вопроса?

2022-10-07 03:24 UTC, VidgarVii requested changes

2022-10-07 03:24 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
не совсем понимаю, зачем тут было ломать код? ответу нужен вопрос

2022-10-07 03:24 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> -  before_action :find_user, only: %i[start]
когда что-то удаляешь, надо сделать так чтобы это потом работало. Для какого юзера будет начат тест?

2022-10-07 03:24 UTC, VidgarVii commented on app/models/test_passage.rb
> +    answer_ids ? correct_answers.ids.sort == answer_ids.map(&:to_i).sort : false
решается без лишних проверок
correct_answers.ids.sort == answer_ids.**to_a.**map(&:to_i).sort

2022-10-07 03:24 UTC, VidgarVii commented on app/models/test_passage.rb
> +    test.questions.order(:id).where('id > ?', current_question.id).first
этот метод не умеет устанавливать первый вопрос для начала тестирования

2022-10-12 06:09 UTC, VidgarVii requested changes

2022-10-12 06:09 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
не работает

2022-10-12 06:09 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user.tests.push(@test)
не работает

2022-10-12 06:09 UTC, VidgarVii commented on app/models/test_passage.rb
> +    answer_ids ? correct_answers.ids.sort == answer_ids.map(&:to_i).sort : false
не исправлено

2022-10-12 06:09 UTC, VidgarVii commented on app/models/test_passage.rb
> +    test.questions.order(:id).where('id > ?', current_question.id).first
не исправлено

2022-10-12 06:09 UTC, VidgarVii commented on config/routes.rb
> +    end
не исправлено

2022-10-15 07:54 UTC, VidgarVii requested changes

2022-10-15 07:54 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to @test
после создания ресурса принято показывать этот ресурс

2022-10-15 07:54 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
не исправлено

2022-10-15 07:54 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :test_passages
про обязательность dependent уже было сказано на прошлых ТЗ. Не стоит ломать рабочий код

2022-10-15 07:54 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author_test, class_name: 'Test', foreign_key: :author_id
ассоциации has_many всегда пишут во множественном числе.

2022-10-15 07:54 UTC, VidgarVii commented on db/migrate/20220930185753_create_test_passages.rb
> +      t.references :current_questions, foreign_key: true #{ to_table: :questions }
мне не совсем понятно, почему надо комментировать to_table: :questions
Протестируй код!

2022-10-15 16:42 UTC, MadinaAbd commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
> 

не понимаю, что имеется ввиду

2022-10-16 06:01 UTC, VidgarVii requested changes

2022-10-16 06:01 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
Еше раз. Не объявляют колбек для 1 экшена.  Пока это не будет исправлено мы не уедим дальше. Если что-то не понятно пиши в чат.

2022-10-16 06:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
не исправлено

2022-10-16 06:01 UTC, VidgarVii commented on app/models/test_passage.rb
> +    self.current_questions = next_question
next_question уже устанавливается через колбек. Не стоит дублировать вызов метода

2022-10-17 08:14 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
параметр test_id не должен передаваться внутри ресурса вопрос. Он приходит через путь запроса. Смотри на 47 строку

2022-10-18 16:45 UTC, merged