Урок 5
MadinaAbd/Test-Guru pull request #7
Opened 2022-07-30 14:49 UTC by MadinaAbd

2022-07-30 18:36 UTC, BubuntuClu requested changes

2022-07-30 18:36 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, trought: :user_tests
а что такое `user_tests`? откуда оно взялось?

2022-07-30 18:36 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, trought: :user_tests
а что такое `user_tests`? откуда оно взялось?

2022-07-30 18:36 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :category
лучше группировать ассоциации по одинаковости их объявления. сначала все `belongs_to`, потом `has_many`и тд

2022-07-30 18:36 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
у тебя работает эта ассоциация? в консоле проверяла?

2022-07-30 20:37 UTC, MadinaAbd commented on app/models/user.rb
> +  has_many :tests, trought: :user_tests
user_tests соединительная таблица между tests и users

2022-07-31 15:49 UTC, VidgarVii requested changes

2022-07-31 15:49 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-07-31 15:49 UTC, VidgarVii commented on app/models/question.rb
тут лишний отступ https://github.com/rubocop/ruby-style-guide#empty-lines-around-bodies

2022-07-31 15:49 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-07-31 15:49 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :user_tests
не работает, так как нет связи со соединительной моделью

2022-07-31 15:49 UTC, VidgarVii commented on app/models/test.rb
>      joins('JOIN categories ON tests.category_id = categories.id')
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-07-31 15:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :user_tests
так же не работает

2022-07-31 15:49 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test'
звучит очень странно. _Юзер имеет много авторов_
Наверное тут должны быть тесты

2022-08-02 07:08 UTC, VidgarVii requested changes

2022-08-02 07:08 UTC, VidgarVii commented on app/models/user.rb
>      Test.joins('JOIN user_tests ON user_tests.test_id = tests.id')
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

***
```ruby
tests.where(level: level)
```

2022-08-02 07:08 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author, class_name: 'Test', foreign_key: :author_id, dependent: :destroy
название ассоциации звучит очень странно. Что юзер имеет авторов. И название ассоциации has_many всегда должно писаться во множественном числе. 
Скорей всего тут речь должна идти не про авторы. А про созданные собственные тесты.

2022-08-06 13:17 UTC, merged